"""
Write MI-AI pipeline outputs into the calling agent's project (not the MI-AI repo).
"""
from __future__ import annotations

import os
import re
import time
from datetime import datetime
from typing import Any, Dict, List, Optional
from urllib.parse import unquote, urlparse


DEFAULT_OUTPUT_SUBDIR = "MI-AI Reports"


def _file_uri_to_path(uri: str) -> Optional[str]:
    """Convert file:// URI to a local filesystem path."""
    if not uri:
        return None
    parsed = urlparse(uri)
    if parsed.scheme and parsed.scheme != "file":
        return None
    path = unquote(parsed.path or "")
    # Windows file:///C:/... → /C:/... ; leave as-is on Unix
    if os.name == "nt" and path.startswith("/") and len(path) > 2 and path[2] == ":":
        path = path[1:]
    return path or None


def resolve_project_root(
    project_root: Optional[str] = None,
    output_dir: Optional[str] = None,
    mcp_root_uris: Optional[List[str]] = None,
) -> Optional[str]:
    """
    Resolve where to write outputs, in priority order:
    1. explicit output_dir (parent is used as project if it ends with reports subdir — see resolve_output_dir)
    2. explicit project_root
    3. MI_AI_PROJECT_ROOT / MI_AI_OUTPUT_DIR env
    4. first MCP client root (file://)
    """
    if project_root:
        return os.path.abspath(os.path.expanduser(project_root))

    env_project = os.environ.get("MI_AI_PROJECT_ROOT")
    if env_project:
        return os.path.abspath(os.path.expanduser(env_project))

    # If only output_dir is given without project_root, treat its parent as project
    # when it looks like .../MI-AI Reports; otherwise use output_dir as the write target
    # via resolve_output_dir — project root still None here if only output_dir set.
    if output_dir:
        return None  # resolve_output_dir handles absolute output_dir alone

    if mcp_root_uris:
        for uri in mcp_root_uris:
            path = _file_uri_to_path(uri)
            if path and os.path.isdir(path):
                return path
            if path and os.path.exists(os.path.dirname(path)):
                # root might be a file; use its directory
                return os.path.dirname(path) if os.path.isfile(path) else path

    return None


def resolve_output_dir(
    project_root: Optional[str] = None,
    output_dir: Optional[str] = None,
    mcp_root_uris: Optional[List[str]] = None,
) -> Optional[str]:
    """Return the directory where report markdown should be written."""
    if output_dir:
        return os.path.abspath(os.path.expanduser(output_dir))

    env_out = os.environ.get("MI_AI_OUTPUT_DIR")
    if env_out:
        return os.path.abspath(os.path.expanduser(env_out))

    root = resolve_project_root(
        project_root=project_root,
        output_dir=None,
        mcp_root_uris=mcp_root_uris,
    )
    if not root:
        return None

    subdir = os.environ.get("MI_AI_OUTPUT_SUBDIR", DEFAULT_OUTPUT_SUBDIR)
    return os.path.join(root, subdir)


def _safe_slug(text: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^\w\s-]", "", text or "report", flags=re.UNICODE)
    slug = slug.strip().replace(" ", "_")[:max_len] or "report"
    return slug


def write_pipeline_report(
    *,
    title: str,
    report: str,
    transcript: Optional[str] = None,
    bibliography: Optional[str] = None,
    pipeline: str = "mi-ai",
    project_root: Optional[str] = None,
    output_dir: Optional[str] = None,
    mcp_root_uris: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """
    Persist a pipeline result into the caller's project.

    Returns metadata: { output_path, output_dir, project_root, written }.
    Does NOT fall back to the MI-AI repo reports/ folder.
    """
    out_dir = resolve_output_dir(
        project_root=project_root,
        output_dir=output_dir,
        mcp_root_uris=mcp_root_uris,
    )
    resolved_root = resolve_project_root(
        project_root=project_root,
        mcp_root_uris=mcp_root_uris,
    )
    if not out_dir and not resolved_root:
        # try env project again via resolve
        out_dir = resolve_output_dir(mcp_root_uris=mcp_root_uris)

    if not out_dir:
        return {
            "written": False,
            "output_path": None,
            "output_dir": None,
            "project_root": resolved_root,
            "message": (
                "No caller project path available. Pass project_root or output_dir, "
                "set MI_AI_PROJECT_ROOT / MI_AI_OUTPUT_DIR, or enable MCP roots on the client."
            ),
        }

    os.makedirs(out_dir, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{_safe_slug(title)}_{stamp}.md"
    file_path = os.path.join(out_dir, filename)

    body = f"# {title}\n\n"
    body += f"*Generated by MI-AI (`{pipeline}`) on {datetime.now().isoformat(timespec='seconds')}*\n\n"
    body += report or ""
    if bibliography:
        body += f"\n\n## Bibliografía\n{bibliography}\n"
    if transcript:
        body += f"\n\n---\n\n## TRANSCRIPT DE PROCESAMIENTO\n\n```\n{transcript}\n```\n"

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(body)

    return {
        "written": True,
        "output_path": file_path,
        "output_dir": out_dir,
        "project_root": resolved_root or os.path.dirname(out_dir),
        "message": f"Report written to {file_path}",
    }


def attach_output(
    result: Dict[str, Any],
    *,
    title: str,
    project_root: Optional[str] = None,
    output_dir: Optional[str] = None,
    mcp_root_uris: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Merge write metadata into a pipeline result dict."""
    meta = write_pipeline_report(
        title=title,
        report=result.get("report") or "",
        transcript=result.get("transcript"),
        bibliography=result.get("bibliography"),
        pipeline=str(result.get("pipeline") or "mi-ai"),
        project_root=project_root,
        output_dir=output_dir,
        mcp_root_uris=mcp_root_uris,
    )
    out = dict(result)
    out["output"] = meta
    if meta.get("output_path"):
        out["output_path"] = meta["output_path"]
    return out
